### PR TITLE
Add prettier

### PR DESCRIPTION
**Pull request by tobilen**
adresses https://github.com/joshwcomeau/react-flip-move/issues/181

* [X] Add prettier
* [X] Add eslint plugin to lint for prettier rules
* [X] Add npm script to autofix styling (`yarn eslint:fix` / `npm run eslint:fix`)
* [X] Extend linting to include stories folder
* [X] Apply styling to all existing files
* [X] Refactor .eslintrc to JavaScript file. This way, we can lint it, too.
* [X] Add section to readme about linting

The biggest part is the refactoring of the github issue and legacy stories. I was a bit unsure about refactoring the [legacy stories](https://github.com/joshwcomeau/react-flip-move/compare/master...ivx:feature/181?expand=1#diff-94bfe4f5c24f26b8818c6320c78b1ee8). So maybe take an extra good look at those.

### CODE REVIEW

**Comment by Hypnosphi** [comment]
Great work @tobilen! I'll take a look at the stories

**Comment by Hypnosphi** [comment]
How do you feel about adding `lint-staged` and `husky` to run `eslint --fix` for staged files on precommit hook?

**Comment by tobilen** [comment]
that'd basically mean modifying source files as a side effect. not sure thats a good idea

**Comment by Hypnosphi** [comment]
Only those that are already modified in the commit

**Comment by tobilen** [comment]
im not a big fan of git hooks and husky in general. their main purpose is covered by well set up CI systems, and the automation part can be unexpected and unintuitive.

from a more practical standpoint, it apparently  breaks a lot of GUI interfaces (https://github.com/typicode/husky/issues/131, https://github.com/typicode/husky/issues/125, https://github.com/okonet/lint-staged/issues/151, https://github.com/ghooks-org/ghooks/issues/40) or requires a lot of configuration (https://github.com/ghooks-org/ghooks/issues/18) as well

**Comment by Hypnosphi** [comment]
Legacy stories work as expected. Please resolve conflicts and update the docs

**Comment by Hypnosphi** [comment]
By the way, you can now create branches directly in `joshwcomeau/react-flip-move`, this makes it a bit easier for other contributors to checkout =)

**Comment by tobilen** [comment]
alright, thanks. cant merge myself though, no write access.

**Comment by Hypnosphi** [comment]
Oh, looks like you haven't accepted the invite, please check your email

**Comment by joshwcomeau** [comment]
Woohoo! Awesome work :D

**Pull request merged**
