### PR TITLE
Fix typescript typing

### PR DESCRIPTION
**Pull request by joshwcomeau**
Quick fix for #218

@thupi if you could take a look and make sure I understood, that'd be great. Not a typescript user, so it's pretty important someone correct me if this is wrong :)

### CODE REVIEW

**Comment by joshwcomeau** [comment]
Hmm, buncha tests failing as a result. Need someone with Typescript experience to take a look :)

**Comment by thupi** [comment]
@joshwcomeau Hi, 

I took a quick look at your tests for Typings and discovered that you are importing the Component in the test using `import * as FlipMove from 'react-flip-move;` :-) I think the tests may pass if you correct the test in the same way i mentioned in the #218 :-) 

I hasn't been able to test it myself :-) Would yo be able to give it a shot and se if it passes :-) ?

**Comment by vsaarinen** [comment]
I'll try to open a separate PR soon that should fix this.

**Comment by joshwcomeau** [comment]
Thanks for the heads-up @thupi! Makes total sense.

And thanks for tackling this, @vsaarinen!

**Pull request closed without merging**
